export const NOTIFICATION_CHANNELS = {
  IN_APP: 'IN_APP',
  PUSH: 'PUSH',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
} as const;

export const NOTIFICATION_STATUSES = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
} as const;

export const NOTIFICATION_TYPES = {
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_COMPLETED: 'BOOKING_COMPLETED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_COMPLETED: 'REFUND_COMPLETED',
  TRIP_REMINDER: 'TRIP_REMINDER',
  GUIDE_VERIFICATION: 'GUIDE_VERIFICATION',
  HOMESTAY_VERIFICATION: 'HOMESTAY_VERIFICATION',
  REVIEW_REMINDER: 'REVIEW_REMINDER',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
} as const;

export const REVIEW_TARGET_TYPES = {
  GUIDE_SERVICE: 'GUIDE_SERVICE',
  HOMESTAY_PROPERTY: 'HOMESTAY_PROPERTY',
} as const;

export const REVIEW_STATUSES = {
  PENDING: 'PENDING',
  PUBLISHED: 'PUBLISHED',
  HIDDEN: 'HIDDEN',
  REJECTED: 'REJECTED',
} as const;

export const MAX_NOTIFICATION_RETRIES = 3;
